baseURL = 'https://bromanko.com/'
languageCode = 'en-us'
title = 'bromanko on the www'
theme = 'rocinante'
email = 'hello@bromanko.com'

paginate = 5

[markup]
  [markup.highlight]
    style = 'catppuccin-frappe'
