on:
  workflow_dispatch:
  push:

name: "Deploy Site"

jobs:
  deploy:
    name: "Deploy Site"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          # Disable diagnostics
          diagnostic-endpoint: ""
